---- __SF_CONTACTS__ Matches (17 in 10 files) ----
BootupInitConfig.h (plutommi\mmi\Bootup\BootupInc) : #if defined(__SF_CONTACTS__)
common_nvram_editor_data_item.h (custom\common\PLUTO_MMI) : #if defined(__SF_CONTACTS__)
common_nvram_editor_data_item.h (custom\common\PLUTO_MMI) : #if defined(__SF_CONTACTS__)
M205_LHJH_GPRS.mak (projects\M205\M205_LHJH) : COM_DEFS += __SF_CONTACTS__
MainMenuRes.res (projects\M205\M205_LHJH\Resource) : #if defined(__SF_CONTACTS__)
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_CONTACTS__ , $(strip $(MODULE_DEFS))),)                  
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_CONTACTS__ , $(strip $(MODULE_DEFS))),)                  
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_CONTACTS__)
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_CONTACTS__)
mmi_service.mak (make\plutommi\mmi_service) : ifneq ($(filter __SF_CONTACTS__ , $(strip $(MODULE_DEFS))),)                  
nvram_common_config.c (custom\common\PLUTO_MMI) : #if defined(__SF_CONTACTS__)
nvram_common_defs.h (custom\common\PLUTO_MMI) : #if defined(__SF_CONTACTS__)
nvram_common_defs.h (custom\common\PLUTO_MMI) : #if defined(__SF_CONTACTS__)
SmsReceiverSrv.c (plutommi\Service\SmsSrv) : #if defined(__SF_CONTACTS__)
SmsReceiverSrv.c (plutommi\Service\SmsSrv) : #if defined(__SF_CONTACTS__)
SmsReceiverSrv.c (plutommi\Service\SmsSrv) : #if defined(__SF_CONTACTS__)
SmsReceiverSrv.c (plutommi\Service\SmsSrv) : #if defined(__SF_CONTACTS__)
---- __SF_WEATHER__ Matches (13 in 9 files) ----
BootupInitConfig.h (plutommi\mmi\Bootup\BootupInc) : #if defined(__SF_WEATHER__)
common_nvram_editor_data_item.h (custom\common\PLUTO_MMI) : #if defined(__SF_WEATHER__)
common_nvram_editor_data_item.h (custom\common\PLUTO_MMI) : #if defined(__SF_WEATHER__)
M205_LHJH_GPRS.mak (projects\M205\M205_LHJH) : COM_DEFS += __SF_WEATHER__
MainMenuRes.res (projects\M205\M205_LHJH\Resource) : #if defined(__SF_WEATHER__)
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_WEATHER__ , $(strip $(MODULE_DEFS))),)                  
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_WEATHER__ , $(strip $(MODULE_DEFS))),)                  
mmi_framework.mak (make\plutommi\mmi_framework) : ifneq ($(filter __SF_WEATHER__ , $(strip $(MODULE_DEFS))),)                  
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_WEATHER__)
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_WEATHER__)
nvram_common_config.c (custom\common\PLUTO_MMI) : #if defined(__SF_WEATHER__)
nvram_common_defs.h (custom\common\PLUTO_MMI) : #if defined(__SF_WEATHER__)
nvram_common_defs.h (custom\common\PLUTO_MMI) : #if defined(__SF_WEATHER__)
---- __SF_REGISTER__ Matches (15 in 10 files) ----
BootupInitConfig.h (plutommi\mmi\Bootup\BootupInc) : #if defined(__SF_REGISTER__)
CallLogCallTime.c (plutommi\mmi\CallLog\CallLogSrc) : #if defined(__SF_REGISTER__)
common_nvram_editor_data_item.h (custom\common\PLUTO_MMI) : #if defined(__SF_REGISTER__)
common_nvram_editor_data_item.h (custom\common\PLUTO_MMI) : #if defined(__SF_REGISTER__)
M205_LHJH_GPRS.mak (projects\M205\M205_LHJH) : COM_DEFS += __SF_REGISTER__
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_REGISTER__ , $(strip $(MODULE_DEFS))),)                  
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_REGISTER__ , $(strip $(MODULE_DEFS))),)                  
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_REGISTER__)
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_REGISTER__)
NITZ.c (plutommi\mmi\NITZHandler\NITZSource) : #if defined(__SF_REGISTER__)
nvram_common_config.c (custom\common\PLUTO_MMI) : #if defined(__SF_REGISTER__)
nvram_common_defs.h (custom\common\PLUTO_MMI) : #if defined(__SF_REGISTER__)
nvram_common_defs.h (custom\common\PLUTO_MMI) : #if defined(__SF_REGISTER__)
SSCPassEngine.c (plutommi\AppCore\SSC) : #if defined(__SF_REGISTER__)
SSCPassEngine.c (plutommi\AppCore\SSC) : #if defined(__SF_REGISTER__)
---- __SF_BASIC_LIB__ Matches (5 in 3 files) ----
M205_LHJH_GPRS.mak (projects\M205\M205_LHJH) : COM_DEFS += __SF_BASIC_LIB__
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_BASIC_LIB__ , $(strip $(MODULE_DEFS))),)                  
mmi_app.mak (make\plutommi\mmi_app) : ifneq ($(filter __SF_BASIC_LIB__ , $(strip $(MODULE_DEFS))),)                  
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_BASIC_LIB__)
mmi_res_range_def.h (plutommi\mmi\Inc) : #if defined(__SF_BASIC_LIB__)
