ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) line 860 : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) line 943 : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) line 1115 : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) line 1404 : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_profiles_set_inline_item in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_entry_customize_scrn in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) :         #if !defined (__MMI_PROF_SLIM_PROFILES__) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_entry_customize_scrn in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : 	  #if !defined (__MMI_PROF_SLIM_PROFILES__) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_get_original_settings in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_get_cur_settings in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_save_cur_settings in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__))|| defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_customize_scrn_csk_hdlr in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) :     #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_progress_bar_value_change_hdlr in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : 	#if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_handfree_volume_sync_callback in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) :     #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_inline_item_highlight_hdlr in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_inline_item_highlight_hdlr in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) :     #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_group_proc in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) :                 #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_group_proc in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) :                 #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
mmi_prof_vol_up_down in ProfilesApp.c (plutommi\mmi\PROFILES\ProfilesSrc) : #if !(defined(__MMI_MAINLCD_96X64__) || defined(__MMI_PROF_SLIM_PROFILES__)) || defined (__KM_PROF_ADD_SMS_TONE_VOL__)
