const GUIITEM_LAYOUT_DATA_T s_item_layout_1line_check_icon =
{
    MMI_LIST_ITEM_HEIGHT,
    {
        { MMI_LIST_ICON_LEFT_SPACE, 1,  MMI_LIST_ITEM_BIG_ICON_WIDTH + MMI_LIST_ICON_LEFT_SPACE,  MMI_LIST_ITEM_HEIGHT - 2 },       /* 1 */
        { MMI_LIST_ITEM_BIG_ICON_WIDTH + MMI_LIST_ICON_LEFT_SPACE + MMI_LIST_TEXT_LEFT_SPACE, 0,  MMI_LIST_ITEM_RIGHT - (MMI_LIST_ITEM_BIG_ICON_WIDTH + MMI_LIST_ICON_LEFT_SPACE), MMI_LIST_ITEM_HEIGHT - 1 },       /* 2 */
        { MMI_LIST_ITEM_RIGHT - (MMI_LIST_ITEM_BIG_ICON_WIDTH), 1,  MMI_LIST_ITEM_RIGHT,  MMI_LIST_ITEM_HEIGHT - 2 },       /* 1 */
        { 0 },
        { 0 },
        { 0 }
    },
    { MMI_LIST_ITEM_RIGHT - MMI_LIST_ITEM_SELECT_ICON_WIDTH, 1, MMI_LIST_ITEM_RIGHT, MMI_LIST_ITEM_HEIGHT - 2 },
    { 0 },
};
