const U8 category83[] = 
{
    6,
    DM_BASE_LAYER_START,
    DM_SCR_BG,
    DM_CATEGORY_CONTROLLED_AREA,
    DM_CALENDAR,
    //DM_STATUS_BAR1,
    DM_BUTTON_BAR1,
    DM_STRING
};
const S16 coordinate_set83[] = 
{
    DM_FULL_SCREEN_COORDINATE_FLAG,
    0, 0, MAIN_LCD_DEVICE_WIDTH, MAIN_LCD_DEVICE_HEIGHT, DM_NO_FLAGS,
    DM_CONTENT_COORDINATE_FLAG,
    //DM_DEFAULT_STATUS_BAR_FLAG,
    DM_DEFAULT_BUTTON_BAR_FLAG, MMI_SOFTKEY_WIDTH,
    /* Status String */
    0, 0, MAIN_LCD_DEVICE_WIDTH, 22, DM_CENTRE_ALIGN_X | DM_STRING_BORDERED,
};
