### str_table1.xls
English, 英语
SIMpleChinese, 简体中文
Norwegian, 挪威
Swedish, 瑞典
Finnish, 芬兰
Lithuanian, 立陶宛语
Ukrainian, 乌克兰
Punjabi, 旁遮普语
Gujarati, 古吉拉特语
Oriya, 奥里亚语
Kannada, 卡纳达语
Malayalam, 马拉雅拉姆语
Lao, 老挝
armenian, 亚美尼亚人
Amharic, 阿姆哈拉语
Uyghur, 维吾尔族
Yoruba, 约鲁巴语
Xhosa, 科萨语
Zulu, 祖鲁语
Assamese, 阿萨姆语
Sesotho, 塞索托
Serbian, 塞尔维亚
Moldovan, 摩尔多瓦
Macedonian, 马其顿语
Latvian, 拉脱维亚语
Kazakh, 哈萨克语
Irish, 爱尔兰语
Igbo, 伊博语
Icelandic, 冰岛的
Hausa, 豪萨
Georgian, 格鲁吉亚语
Calician, 卡利西安
Filipino, 菲律宾人
Estonian, 爱沙尼亚语
Catalan, 加泰罗尼亚语
Basque, 巴斯克
Azerbaijani, 阿塞拜疆
Albanian, 阿尔巴尼亚语
Afrikaans, 南非荷兰语
Croatian, 克罗地亚语
Tibetan, 藏
hangul, 韩文
Sinhala, 僧伽罗语
Uzbekstan, 乌兹别克斯坦
Nepali, 尼泊尔语
Latin-Spanish, 拉丁-西班牙语
Latin-Serbian, 拉丁-塞尔维亚语
Portuguese-BR, 葡萄牙语-BR
