@echooff
F:
set proD=F:\11CW1352MP_BLEPHONE61D_11C_V33\

cd %proD%


rmdir /s/q .\build

rmdir /s/q .\pl_lib_size
rmdir /s/q .\plutommi\Customer\Res_MMI
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\dep\common
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\dep\resgen
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\dep\xml_parser
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\dep
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj\font_gen
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj\mtk_resgenerator
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj\mtk_resgenerator_core
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj\mtk_resgenerator_xml
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj\plmncreate
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj\ref_list_merge
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj\resgen_xml
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\obj
rmdir /s/q .\plutommi\Customer\ResGenerator\debug\res
rmdir /s/q .\plutommi\Customer\ResGenerator\debug
rmdir /s/q .\plutommi\Customer\ResGenerator\temp\ref_list
rmdir /s/q .\plutommi\Customer\ResGenerator\temp\res
rmdir /s/q .\plutommi\Customer\ResGenerator\temp\res_out\CustomerInc
rmdir /s/q .\plutommi\Customer\ResGenerator\temp\res_out\custresource
rmdir /s/q .\plutommi\Customer\ResGenerator\temp\res_out\res
rmdir /s/q .\plutommi\Customer\ResGenerator\temp\res_out
rmdir /s/q .\plutommi\Customer\ResGenerator\temp
rmdir /s/q .\tst\database_classb\msglog_db


del /s/q .\~lis_temp
del /s/q .\MoDIS_VC9\MoDIS\CustMMI3rdROM
del /s/q .\plutommi\Customer\CustResource\CustMMI3rdROM
del /s/q .\plutommi\Customer\ResGenerator\null
del /s/q .\plutommi\Customer\ResGenerator\TEMPIMAGE
del /s/q .\plutommi\mmi\GlobalTargetPathDef
rem ##### del /s/q .\tst\database_classb\BPLGUInfoCustomApp_MT6261_S00_MAUI_11C_W13_52_MP_V33_F1
del /s/q .\tst\database_classb\BPLGUInfoCustomAppSrcP_MT6261_S00_M107_XYZN_S2_4A_NEDADJ_F5_V04_T01_20181207
del /s/q .\tst\database_classb\DbgInfo_11CW1352MP_M107_XYZN_S2_4A_NEDADJ_F6_M107_XYZN_S2_4A_NEDADJ_F5_V04_T01_20181207_2018_12_07_14_23
del /s/q .\tst\database_classb\enumFileCustomAppSrc

del /s/q .\AAPMC.log
del /s/q .\auto_reset.cmm
del /s/q .\BOOTLOADER_M107_XYZN_S2_4A_NEDADJ_F6_MT6261_nocode.cmm
del /s/q .\custom\app\BLEPHONE61D_11C_BB\nvram_mmi_cache_cust_pack.h
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\adc_var.c
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\eint_drv.h
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\eint_var.c
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\gpio_drv.h
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\gpio_var.c
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\gpio_var_v2.c
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\keypad_drv.h
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\pmic_drv.c
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\pmic_drv.h
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\pwm_drv.h
del /s/q .\custom\codegen\BLEPHONE61D_11C_BB\uem_drv.c
del /s/q .\custom\common\custom_mmi_cache_cat.xml
del /s/q .\custom\common\hal\nvram\custom_nvram_lid_cat.xml
del /s/q .\custom\system\BLEPHONE61D_11C_BB\combo_flash_config.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\combo_flash_id.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\combo_sfi_config.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\combo_sfi_defs.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_blconfig.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_config.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_config.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_demp.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_demp.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_EMI.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_EMI_INFO.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_EMI_release.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_FeatureConfig.h.beforeAutoAdj1544164545.93
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_flash.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_flash_norfdm5.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_fota.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_fota.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_img_config.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_img_config.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_jump_tbl.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_jump_tbl.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_scatstruct.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_scatstruct.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_scatstruct_fota.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_scatstruct_fota.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_sds_dp.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_sds_dp.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_sds_type.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_secure_config.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_SFI.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_sfi_clock.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_util.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\custom_util.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\flash_opt_gen.h
del /s/q .\custom\system\BLEPHONE61D_11C_BB\fs_config.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\maui_MBA_info.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\resource_custpack_preamble.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\resource_lang_pack_preamble.c
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\FeatureBased\ObjListGen\object.list.backup
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\FeatureBased\ObjListGen\objectALICE.list
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\FeatureBased\ObjListGen\objectALICE.list.beforeAutoAdj1544164545.641
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\FeatureBased\ObjListGen\objectROM1.list
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\FeatureBased\ObjListGen\objectROM1.list.beforeAutoAdj1544164545.355
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\FeatureBased\ObjListGen\objectZIMAGE.list
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\FeatureBased\ObjListGen\objectZIMAGE.list.beforeAutoAdj1544164545.300
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scat_config\RegionConfig\DCMP.csv.1544164545.590
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scatBL_MT6261.txt
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scatBL_MT6261_ext.txt
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scatM107_XYZN_S2_4A_NEDADJ_F6.txt
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scatM107_XYZN_S2_4A_NEDADJ_F6.txt.dummy
del /s/q .\custom\system\BLEPHONE61D_11C_BB\scatM107_XYZN_S2_4A_NEDADJ_F6_flashtool.txt
del /s/q .\custom\system\BLEPHONE61D_11C_BB\sys_mem_size.h
del /s/q .\custom\tst\tst_file_default_Catcher_filter.c
del /s/q .\EXT_BOOTLOADER_M107_XYZN_S2_4A_NEDADJ_F6_MT6261_nocode.cmm
del /s/q .\InTargetReset.cmm
del /s/q .\lnkfeedback.txt
del /s/q .\M107_XYZN_S2_4A_NEDADJ_F6_gprs.log
del /s/q .\M107_XYZN_S2_4A_NEDADJ_F6_PCB01_gprs_MT6261_S00_nocode.cmm
del /s/q .\make.ini
del /s/q .\make\app_cfg.mak
del /s/q .\make\M107_XYZN_S2_4A_NEDADJ_F6_GPRS.mak
del /s/q .\make\Verno_M107_XYZN_S2_4A_NEDADJ_F6.bld
del /s/q .\make\~DbgInfoGen.cfg
rem ### del /s/q .\mct.ini
del /s/q .\nvram_lid_size_merge.log
del /s/q .\pl.ini
del /s/q .\pl.log
del /s/q .\pl.tmp
del /s/q .\pl_error_normal.log
del /s/q .\pl_timestamp.txt
del /s/q .\PlinkTime.log
del /s/q .\plutommi\Customer\CustomerInc\CustResDef.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_cache_default_value.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_cache_nvram_editor.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_cache_table.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_all_defs.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_alarm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_am_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_apn_control_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_appmgr_test_1_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_appmgr_test_2_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_appmgr_test_3_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_appmgr_test_4_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_audioplayer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_auto_rotate_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_azaan_alarm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_bluetooth_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_bootup_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_bt_dialer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_calculator_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_calendar_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_calibration_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_calllog_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_callset_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_camco_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_camera_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_cb_mgr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_cbm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_charger_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_connectivity_mainmenu_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_customer_service_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_data.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_data_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_dataaccount_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_devapp_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_dialer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_engineermode1_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_extra_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_factorymode_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_filemanager_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_fmrdo_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_font_effects_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_font_manager_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_funandgames_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_games_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_gpio_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_hijri_calendar_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_idle_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_idle_homescreen_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_idle_nmgr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_imageflow_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_imageviewer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_lunar_query_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mainmenu_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mediawall_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mem_config.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mmi_certman_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mobile_service_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mobile_tracker_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mode_switch_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mre_appmgr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mre_bg_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_mre_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_netset_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_nitz_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_note_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_nss_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_ntp_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_nw_info_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_organizer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_package_concurrent_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_phonebook_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_phonesetting_new_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_profiles_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_reminder_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_restore_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_sat_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_scr_locker_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_scr_saver_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_search_web_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_security_setting_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_services_sat_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_setting_download_cal_data_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_setting_menu_effect_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_setting_new_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_setting_version_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_shellapp_base_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_shortcuts_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_shutdown_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_sim_ctrl_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_simspace_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_sms_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_soundrecorder_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_ss_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_sso_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_stopwatch_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_syncml_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_todolist_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_tts_setting_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_ucm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_ucmbt_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_udx_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_uiframework_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_unifiedmessage_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_usbmmi_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_usbsrv_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_vdoply_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_vdorec_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_audioplayer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_calendar_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_clock_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_date_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_event_inbox_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_fmradio_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_memo_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_mobile_internet_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_mre_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_next_alarm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_operator_name_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_pet_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_photo_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_profile_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_snow_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_homescreen_wg_wo_store_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_hs_todo_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_hs_wg_baidu_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_hs_wg_bkm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_notepaper_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_shell_fc_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_shell_iv_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_shell_mediaplayer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_shell_msg_viewer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_shell_scrlock_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_venus_shell_settings_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_viewsetting_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_webcam_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_app_worldclock_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_callback_mgr_config.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_callback_mgr_header_file.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_core_ucm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_alert_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_dialer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_imageviewer_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_password_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_sim_sel_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_sso_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_toneselector_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_use_detail_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_cui_verify_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_file_type_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_framework_asm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_img_misc_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_mainmenu_launch.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_menu_misc_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_menu_shortcut_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_motion_sensor_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_native_app_package_data.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_alarm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_appmgr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_bootup_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_btcm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_btsco_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_calllog_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_callset_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_cbm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_charbat_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_cnmgr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_cphs_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_datalock_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_datetime_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_dtcnt_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_editor_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_filemanager_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_flight_mode_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_fullscreen_editor_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_gcall_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_gdi_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_general_setting_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_gpio_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_gps_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_inline_editor_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_input_method_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_aud_info_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_audply_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_autorama_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_cap_hdr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_cap_mav_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_cap_vga_below_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_full_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_only_cap_lcd_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_only_cap_lcd_disable_jaia_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_camera_standard_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_a_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_cif_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_info_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_mp4_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_preview_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_qvga_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_qvga_mpeg4sp_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_subtitle_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdoply_v_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdorec_cif_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mdi_vdorec_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mmi_charset_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_mmi_theme_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_modeswitch_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_netset_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_nitz_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_nmgr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_nw_info_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_nw_name_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_pen_calibration_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_phb_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_phnset_onoff_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_prof_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_reminder_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_restore_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_safe_mode_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_sat_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_screensaver_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_secset_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_sensor_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_shutdown_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_sim_ctrl_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_sms_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_soundrec_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_spof_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_ss_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_status_icons_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_syncml_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_ucm_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_unifiedmessage_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_vbookmark_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_vcalendar_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_vcard_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_venus_component_normal_mode_menu_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_venus_theme_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_virtual_keyboard_misc_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_vobject_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_wallpaper_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_srv_wgtmgr_def.h
del /s/q .\plutommi\Customer\CustomerInc\mmi_rp_vapp_video_player_cp_def.h
del /s/q .\plutommi\Customer\CustomerInc\screen_enum.h
del /s/q .\plutommi\Customer\CustResource\CustAdoDataHW.h
del /s/q .\plutommi\Customer\CustResource\CustAdoDataHWExt.h
del /s/q .\plutommi\Customer\CustResource\CustAdoRes.c
del /s/q .\plutommi\Customer\CustResource\CustAdoResExt.c
del /s/q .\plutommi\Customer\CustResource\CustBootupImgData.h
del /s/q .\plutommi\Customer\CustResource\CustImg3rdROM.bin
del /s/q .\plutommi\Customer\CustResource\custimgdatahw.h
del /s/q .\plutommi\Customer\CustResource\custimgdatahwBak.h
del /s/q .\plutommi\Customer\CustResource\CustImgDataHWExt.h
del /s/q .\plutommi\Customer\CustResource\CustImgDataMeta.txt
del /s/q .\plutommi\Customer\CustResource\CustImgDataRes_0.c
del /s/q .\plutommi\Customer\CustResource\CustImgDataRes_1.c
del /s/q .\plutommi\Customer\CustResource\CustImgDataRes_2.c
del /s/q .\plutommi\Customer\CustResource\CustImgDataRes_3.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroup3rdROMMap.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroup3rdROMRes.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupDataHW.h
del /s/q .\plutommi\Customer\CustResource\CustImgGroupDataRes_0.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupDataRes_1.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupDataRes_2.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupDataRes_3.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupMap.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupRes.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupSingleData3rdROMHW.h
del /s/q .\plutommi\Customer\CustResource\CustImgGroupSingleData3rdROMRes.c
del /s/q .\plutommi\Customer\CustResource\CustImgGroupSingleDataHW.h
del /s/q .\plutommi\Customer\CustResource\CustImgGroupSingleDataRes.c
del /s/q .\plutommi\Customer\CustResource\CustImgMap.c
del /s/q .\plutommi\Customer\CustResource\CustImgMapExt.c
del /s/q .\plutommi\Customer\CustResource\CustImgMapMeta.txt
del /s/q .\plutommi\Customer\CustResource\CustImgRes.c
del /s/q .\plutommi\Customer\CustResource\CustImgResExt.c
del /s/q .\plutommi\Customer\CustResource\CustMenuRes.c
del /s/q .\plutommi\Customer\CustResource\CustMenuTree_Out.c
del /s/q .\plutommi\Customer\CustResource\CustMenuTreeID_Out.c
del /s/q .\plutommi\Customer\CustResource\CustMMI3rdROM.h
del /s/q .\plutommi\Customer\CustResource\CustStr3rdROM.bin
del /s/q .\plutommi\Customer\CustResource\CustStrList.txt
del /s/q .\plutommi\Customer\CustResource\CustStrMap.c
del /s/q .\plutommi\Customer\CustResource\CustStrMap.c.comp.bak
del /s/q .\plutommi\Customer\CustResource\CustStrMapComp.c
del /s/q .\plutommi\Customer\CustResource\CustStrMapMeta.txt
del /s/q .\plutommi\Customer\CustResource\CustStrRes.c
del /s/q .\plutommi\Customer\CustResource\CustStrRes.c.comp.bak
del /s/q .\plutommi\Customer\CustResource\CustStrResComp.c
del /s/q .\plutommi\Customer\CustResource\CustStrResMeta.txt
del /s/q .\plutommi\Customer\CustResource\CustStrSearchComp.c
del /s/q .\plutommi\Customer\CustResource\CustVenusThemeId.h
del /s/q .\plutommi\Customer\CustResource\FontData.c
del /s/q .\plutommi\Customer\CustResource\FontRes.c
del /s/q .\plutommi\Customer\CustResource\mmi_cache_table.c
del /s/q .\plutommi\Customer\CustResource\mmi_rp_app_data.c
del /s/q .\plutommi\Customer\CustResource\mmi_rp_callback_mgr_table.c
del /s/q .\plutommi\Customer\CustResource\mmi_rp_file_type_table.c
del /s/q .\plutommi\Customer\CustResource\mmi_rp_img_misc_data.c
del /s/q .\plutommi\Customer\CustResource\mmi_rp_menu_misc_data.c
del /s/q .\plutommi\Customer\CustResource\mmi_rp_menu_shortcut_data.c
del /s/q .\plutommi\Customer\CustResource\mmi_rp_native_app_package_data.c
rem ### del /s/q .\plutommi\Customer\CustResource\mslt_region.ini
del /s/q .\plutommi\Customer\CustResource\mte_img_resource.h
rem ### del /s/q .\plutommi\Customer\CustResource\VKV2.INI
rem ### del /s/q .\plutommi\Customer\CustResource\XML.rar
del /s/q .\plutommi\Customer\FontResgen\font_gen.exe
del /s/q .\plutommi\Customer\FontResgen\res_gen_font.cpp
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_EGG.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_EGG_NEXT_STAGE.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_BODY_DOWN_LEFT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_BODY_DOWN_RIGHT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_BODY_RIGHT_LEFT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_BODY_UP_DOWN.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_BODY_UP_LEFT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_BODY_UP_RIGHT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_HEAD_DOWN.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_HEAD_LEFT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_HEAD_RIGHT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_HEAD_UP.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_TAIL_DOWN.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_TAIL_LEFT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_TAIL_RIGHT.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_SNAKE_TAIL_UP.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\GAME_SNAKE_WALL.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\gameover\GRADESMAP.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\gameover\PIC.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\multi_lan\GAMEOVER.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\multi_lan\GAMEOVER_C.BMP.ABM
del /s/q .\plutommi\Customer\Images\GameImages\Snake\SNAKE.BMP.ABM
del /s/q .\plutommi\Customer\remakeResource.bat
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_alarm.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_audioplayer.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_azaan_alarm.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_bluetooth.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_calculator.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_calendar.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_calllog.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_callset.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_camera.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_connectivity_mainmenu.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_dataaccount.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_engineermode1.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_factorymode.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_filemanager.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_fmrdo.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_funandgames.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_gpio.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_hijri_calendar.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_imageviewer.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_mainmenu.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_mobile_tracker.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_mode_switch.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_mre.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_netset.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_organizer.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_phonebook.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_phonesetting_new.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_profiles.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_restore.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_sat.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_scr_locker.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_security_setting.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_shortcuts.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_sms.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_soundrecorder.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_ss.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_stopwatch.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_ucm.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_ucmbt.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_unifiedmessage.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_vdoply.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_app_vdorec.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_cui_dialer.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_cui_use_detail.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_populate.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_srv_editor.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_srv_flight_mode.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_srv_phnset_onoff.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_srv_screensaver.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_srv_vobject.c
del /s/q .\plutommi\Customer\res_mmi_xml\mmi_rp_srv_wallpaper.c
del /s/q .\plutommi\Customer\ResGenerator.bat
del /s/q .\plutommi\Customer\ResGenerator\AutoAnalysis\image_info_all_converted.txt
del /s/q .\plutommi\Customer\ResGenerator\custom_include.txt
del /s/q .\plutommi\Customer\ResGenerator\custom_option.txt
del /s/q .\plutommi\Customer\ResGenerator\font_gen.exe
del /s/q .\plutommi\Customer\ResGenerator\handwritingresgen.log
del /s/q .\plutommi\Customer\ResGenerator\mtk_resgenerator.exe
del /s/q .\plutommi\Customer\ResGenerator\mtk_resgenerator.map
del /s/q .\plutommi\Customer\ResGenerator\offline_post_xml_legacy_image_repo.txt
del /s/q .\plutommi\Customer\ResGenerator\offline_pre_xml_legacy_image_repo.txt
del /s/q .\plutommi\Customer\ResGenerator\offline_pre_xml_legacy_string_repo.txt
del /s/q .\plutommi\Customer\ResGenerator\offline_xml_audio_repo.txt
del /s/q .\plutommi\Customer\ResGenerator\offline_xml_image_repo.txt
del /s/q .\plutommi\Customer\ResGenerator\offline_xml_string_repo.txt
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\AudioResParam.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\BinaryModeResGen.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\BinaryResParam.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\ExternalCMDManager.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\GeneralResDAO.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\GeneralResParam.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\GeneralResParamModel.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\ImageResParam.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\OfflineResHelper.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\OfflineResId.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\OfflineResPopCAPI.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\OfflineResPopDefaultAdaptor.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\stdafx.o
del /s/q .\plutommi\Customer\ResGenerator\OfflineResGenerator\lib\common\StringResParam.o
del /s/q .\plutommi\Customer\ResGenerator\PhnsetAutoGen.log
del /s/q .\plutommi\Customer\ResGenerator\plmncreate.exe
del /s/q .\plutommi\Customer\ResGenerator\ref_list_merge.exe
del /s/q .\plutommi\Customer\ResGenerator\resgen_inc.txt
del /s/q .\plutommi\Customer\ResGenerator\resgen_time.log
del /s/q .\plutommi\Customer\ResGenerator\resgen_xml.exe
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\CATResGenerator.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\ImageGroupCreator.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\ResgenCatUtilCAPI.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\ResgenConfigurator.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\ResgenConfiguratorCAPI.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\ResgenCrashHandlingServ.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\StringCompressionBuffer.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenCore\lib\common\StringCompressionBufferCAPI.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenLog\lib\common\ResgenLog.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenLog\lib\common\ResgenLogCAPI.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenLog\lib\common\ResgenLogFilter.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenLog\lib\common\ResgenLogger.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenLog\lib\common\ResgenLogHandler.o
del /s/q .\plutommi\Customer\ResGenerator\ResgenLog\lib\common\ResgenLogManager.o
del /s/q .\plutommi\Customer\ResGenerator\strmap_1.bin
del /s/q .\plutommi\Customer\ResGenerator\strmap_1.compress
del /s/q .\plutommi\Customer\ResGenerator\strmap_2.bin
del /s/q .\plutommi\Customer\ResGenerator\strmap_2.compress
del /s/q .\plutommi\Customer\ResGenerator\strmap_3.bin
del /s/q .\plutommi\Customer\ResGenerator\strmap_3.compress
del /s/q .\plutommi\Customer\ResGenerator\strmap_4.bin
del /s/q .\plutommi\Customer\ResGenerator\strmap_4.compress
del /s/q .\plutommi\Customer\ResGenerator\strmap_5.bin
del /s/q .\plutommi\Customer\ResGenerator\strmap_5.compress
del /s/q .\plutommi\Customer\ResGenerator\strmap_FIXED.bin
del /s/q .\plutommi\Customer\ResGenerator\strmap_FIXED.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_1.bin
del /s/q .\plutommi\Customer\ResGenerator\strres_1.bin.decompress
del /s/q .\plutommi\Customer\ResGenerator\strres_1.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_1bin.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_2.bin
del /s/q .\plutommi\Customer\ResGenerator\strres_2.bin.decompress
del /s/q .\plutommi\Customer\ResGenerator\strres_2.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_2bin.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_3.bin
del /s/q .\plutommi\Customer\ResGenerator\strres_3.bin.decompress
del /s/q .\plutommi\Customer\ResGenerator\strres_3.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_3bin.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_4.bin
del /s/q .\plutommi\Customer\ResGenerator\strres_4.bin.decompress
del /s/q .\plutommi\Customer\ResGenerator\strres_4.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_4bin.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_5.bin
del /s/q .\plutommi\Customer\ResGenerator\strres_5.bin.decompress
del /s/q .\plutommi\Customer\ResGenerator\strres_5.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_5bin.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_dup.bin
del /s/q .\plutommi\Customer\ResGenerator\strres_dup.compress
del /s/q .\plutommi\Customer\ResGenerator\strres_FIXED.bin
del /s/q .\plutommi\Customer\ResGenerator\strres_FIXED.compress
del /s/q .\plutommi\Customer\ResGenerator\ThemeXML\Log\venus_theme_generator.log
del /s/q .\plutommi\Customer\ResGenerator\xml_time.log
del /s/q .\plutommi\Customer\ResGenerator_HW.bat
del /s/q .\plutommi\Customer\ResGenerator_XML.bat
del /s/q .\plutommi\Customer\UpdateSkin.bat
del /s/q .\plutommi\Framework\EventHandling\EventsInc\mmi_menu_handlers.h
del /s/q .\plutommi\Framework\MSLT\MSLTInc\MSLT_INFO\mmi_mslt_language.txt
del /s/q .\plutommi\Framework\MSLT\MSLTInc\MSLT_INFO\mmi_mslt_string.txt
del /s/q .\plutommi\Framework\MSLT\MSLTInc\mslt_modis.h
del /s/q .\plutommi\mmi\Inc\MMI_features_switch.h
del /s/q .\plutommi\mmi\MiscFramework\MiscFrameworkInc\PlmnEnum.h
del /s/q .\plutommi\mmi\TargetOption.txt
del /s/q .\plutommi\Service\NetSetSrv\PlmnName.c
del /s/q .\plutommi\VendorApp\ResGenerator\resgen_xml.exe
del /s/q .\tools\NVRAMStatistic\debug\adc_nvram_def.o
del /s/q .\tools\NVRAMStatistic\debug\audio_nvram_def.o
del /s/q .\tools\NVRAMStatistic\debug\camera_nvram_def.o
del /s/q .\tools\NVRAMStatistic\debug\custom_nvram_cat.o
del /s/q .\tools\NVRAMStatistic\debug\custom_nvram_sec.o
del /s/q .\tools\NVRAMStatistic\debug\mmi_gps_nvram_def.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_auto_gen.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_common_config.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_cust_pack.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_data_items.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_factory_config.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_gen_mmi_cache.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_gen_util.o
del /s/q .\tools\NVRAMStatistic\debug\nvram_user_config.o
del /s/q .\tools\NVRAMStatistic\debug\touchpanel_nvram_def.o
del /s/q .\tools\NVRAMStatistic\debug\ul1_nvram_def.o
del /s/q .\tools\NVRAMStatistic\debug\userprofile_nvram_def.o
del /s/q .\tools\RVCTBuildNo.tmp
del /s/q .\tst\database\log2SD_Catcher_filters.ini
del /s/q .\tst\database\sf.ini
rem ### del /s/q .\tst\database_classb\_BPLGUInfoCustomApp_MT6261_S00_MAUI_11C_W13_52_MP_V33_F1.check
del /s/q .\tst\database_classb\_BPLGUInfoCustomAppSrcP_MT6261_S00_M107_XYZN_S2_4A_NEDADJ_F5_V04_T01_20181207.check
del /s/q .\tst\database_classb\catcher_filter.bin
del /s/q .\tst\database_classb\cgen.cfg
del /s/q .\tst\database_classb\codegen.lis
del /s/q .\tst\database_classb\CompTrcDefs.lst
del /s/q .\tst\database_classb\custom_databaseinfo.csv
rem ###  del /s/q .\tst\database_classb\MCDDLL.dll
rem ###  del /s/q .\tst\database_classb\MTK_databaseinfo.csv
del /s/q .\tst\database_classb\pstrace_db\abm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\adr_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\atci_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\bluetooth_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\bmc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\btdrv_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\cc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\certman_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ciss_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\cmux_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\codegen_single.h
del /s/q .\tst\database_classb\pstrace_db\codegen_single.ptr
del /s/q .\tst\database_classb\pstrace_db\csce_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\cse_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\csm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\csr_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\dak_trace_msg_gen.h
del /s/q .\tst\database_classb\pstrace_db\dbme_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\demp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\dhcp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\dhcpd_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\dm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\dp_engine_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\dps_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\drlc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\drm_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\dt_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\email_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\ems_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\event_info_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ex_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\exp_SphLoggingDb_gen.h
del /s/q .\tst\database_classb\pstrace_db\ext_modem_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\fa_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\flc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\gps_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\http_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ike_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\imps_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\init_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\iperf_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ircomm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\irda_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\j2me_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\keypad_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\l1a_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\l2r_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\lapdm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\lcl_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ll1_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\llc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\m3d_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\m3g_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\mac_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\meme_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\mm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\mpal_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\mpal_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\mtp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\obex_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\opera_adp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ossl_crypto_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ossl_os_adp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ossl_pki_adp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ossl_pki_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ossl_ssl_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ossl_ssladp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\pdcp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\poc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ppp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ps_trace.h
del /s/q .\tst\database_classb\pstrace_db\rabm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rac_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ratcm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ratdm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rfc2507_lib_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rlc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rlp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rndis_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rr_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rrce_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rrlp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rsvag_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rsvak_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rsvas_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rsvau_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rtc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\rtsp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\saf_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\scsi_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sdp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\seclib_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\seq_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\siano_cmmb_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sibe_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sip_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\slce_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sms_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\smsal_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\smu_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\snd_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\soc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sqlite3_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\sslplus5_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\SST_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\supc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\supl_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\syncml_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\t30_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\tcm_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\tcpip_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\tdt_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\tls_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\touch_panel_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\tst_trace_gen.h
del /s/q .\tst\database_classb\pstrace_db\TVT_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\uagps_cp_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\uagps_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\uagps_up_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\udps_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ul1a_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ul2_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\umac_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ups_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\urlc_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\urr_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\usime_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\vadp_app_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\vadp_sys_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\voip_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\vrt_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\VT_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\wmt_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\wndrv_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ws_ps_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\ws_trc_gen.h
del /s/q .\tst\database_classb\pstrace_db\xdm_trc_gen.h
del /s/q .\vendor\font\inc\L_Farsi_small.h
del /s/q .\verno\verno.h
del /s/q .\~custom_EMI_c.tmp
del /s/q .\~flash_cfg_tmp.c
del /s/q .\~fs_quota_usage.log
del /s/q .\~net_path.tmp
del /s/q .\~nvram_lid_information.log
del /s/q .\~nvram_lid_size.log
del /s/q .\~reg_base_after_precompile.tmp
del /s/q .\~reg_base_after_transform.tmp
del /s/q .\~syscomp_config.o




pause

